//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowd.Web.user {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuserID;
		protected global::System.Web.UI.WebControls.TextBox txtuserName;
		protected global::System.Web.UI.WebControls.TextBox txtuserPwd;
		protected global::System.Web.UI.WebControls.TextBox txtuserEmail;
		protected global::System.Web.UI.WebControls.TextBox txtbirthday;
		protected global::System.Web.UI.WebControls.CheckBox chksex;
		protected global::System.Web.UI.WebControls.TextBox txtGschool;
		protected global::System.Web.UI.WebControls.TextBox txtDschool;
		protected global::System.Web.UI.WebControls.TextBox txtcompany;
		protected global::System.Web.UI.WebControls.TextBox txtdescribe;
		protected global::System.Web.UI.WebControls.TextBox txtlocation;
		protected global::System.Web.UI.WebControls.TextBox txtprofession;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
