//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowd.Web.user {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbluserID;
	protected global::System.Web.UI.WebControls.Label lbluserName;
	protected global::System.Web.UI.WebControls.Label lbluserPwd;
	protected global::System.Web.UI.WebControls.Label lbluserEmail;
	protected global::System.Web.UI.WebControls.Label lblbirthday;
	protected global::System.Web.UI.WebControls.Label lblsex;
	protected global::System.Web.UI.WebControls.Label lblGschool;
	protected global::System.Web.UI.WebControls.Label lblDschool;
	protected global::System.Web.UI.WebControls.Label lblcompany;
	protected global::System.Web.UI.WebControls.Label lbldescribe;
	protected global::System.Web.UI.WebControls.Label lbllocation;
	protected global::System.Web.UI.WebControls.Label lblprofession;


       
    }
}
