//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowd.Web.admin {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtadminID;
		protected global::System.Web.UI.WebControls.TextBox txtadminName;
		protected global::System.Web.UI.WebControls.TextBox txtadminPwd;
		protected global::System.Web.UI.WebControls.CheckBox chkcreatAdmin;
		protected global::System.Web.UI.WebControls.CheckBox chkdeleteAdmin;
		protected global::System.Web.UI.WebControls.CheckBox chkban;
		protected global::System.Web.UI.WebControls.CheckBox chkpostInfo;
		protected global::System.Web.UI.WebControls.CheckBox chksee;
		protected global::System.Web.UI.WebControls.CheckBox chkupdateV;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
